# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model_import_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(950, 475)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_model_path = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_model_path.setFont(font)
        self.label_model_path.setObjectName("label_model_path")
        self.horizontalLayout.addWidget(self.label_model_path)
        self.edit_jnl_path = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edit_jnl_path.setFont(font)
        self.edit_jnl_path.setText("")
        self.edit_jnl_path.setReadOnly(True)
        self.edit_jnl_path.setObjectName("edit_jnl_path")
        self.horizontalLayout.addWidget(self.edit_jnl_path)
        self.btn_temp_load = QtWidgets.QPushButton(Form)
        self.btn_temp_load.setObjectName("btn_temp_load")
        self.horizontalLayout.addWidget(self.btn_temp_load)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.check_btn = QtWidgets.QCheckBox(Form)
        self.check_btn.setObjectName("check_btn")
        self.horizontalLayout_4.addWidget(self.check_btn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3dModel_path = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3dModel_path.setFont(font)
        self.label_3dModel_path.setObjectName("label_3dModel_path")
        self.horizontalLayout_2.addWidget(self.label_3dModel_path)
        self.edit_external_model_path = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edit_external_model_path.setFont(font)
        self.edit_external_model_path.setText("")
        self.edit_external_model_path.setReadOnly(True)
        self.edit_external_model_path.setObjectName("edit_external_model_path")
        self.horizontalLayout_2.addWidget(self.edit_external_model_path)
        self.btn_temp_ext_load = QtWidgets.QPushButton(Form)
        self.btn_temp_ext_load.setObjectName("btn_temp_ext_load")
        self.horizontalLayout_2.addWidget(self.btn_temp_ext_load)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.btn_confirm = QtWidgets.QPushButton(Form)
        self.btn_confirm.setObjectName("btn_confirm")
        self.horizontalLayout_3.addWidget(self.btn_confirm)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.horizontalLayout_3.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.verticalLayout.setStretch(7, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.horizontalLayout_5.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "导入模型"))
        self.label_model_path.setText(_translate("Form", "模型文件路径："))
        self.btn_temp_load.setText(_translate("Form", "载入"))
        self.check_btn.setText(_translate("Form", "三维模型非仿真软件生成"))
        self.label_3dModel_path.setText(_translate("Form", "三维模型路径："))
        self.btn_temp_ext_load.setText(_translate("Form", "载入"))
        self.btn_confirm.setText(_translate("Form", "确认导入"))
