# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Projects\python\radar_project\src\ui\reliability_form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1061, 726)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.table_content = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_content.sizePolicy().hasHeightForWidth())
        self.table_content.setSizePolicy(sizePolicy)
        self.table_content.setSizeIncrement(QtCore.QSize(0, 0))
        self.table_content.setBaseSize(QtCore.QSize(0, 0))
        self.table_content.setObjectName("table_content")
        self.table_content.setColumnCount(4)
        self.table_content.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_content.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_content.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_content.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table_content.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.table_content)
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout1.addWidget(self.label_6)
        self.edit_id_to_del = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edit_id_to_del.setFont(font)
        self.edit_id_to_del.setObjectName("edit_id_to_del")
        self.horizontalLayout1.addWidget(self.edit_id_to_del)
        self.verticalLayout.addLayout(self.horizontalLayout1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.label_4 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout2.addWidget(self.label_4)
        self.btn_mise_reliability = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_mise_reliability.sizePolicy().hasHeightForWidth())
        self.btn_mise_reliability.setSizePolicy(sizePolicy)
        self.btn_mise_reliability.setObjectName("btn_mise_reliability")
        self.horizontalLayout2.addWidget(self.btn_mise_reliability)
        self.btn_press_reliability = QtWidgets.QPushButton(Form)
        self.btn_press_reliability.setObjectName("btn_press_reliability")
        self.horizontalLayout2.addWidget(self.btn_press_reliability)
        self.btn_tresca_reliability = QtWidgets.QPushButton(Form)
        self.btn_tresca_reliability.setObjectName("btn_tresca_reliability")
        self.horizontalLayout2.addWidget(self.btn_tresca_reliability)
        self.verticalLayout.addLayout(self.horizontalLayout2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout3.setObjectName("horizontalLayout3")
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout3.addWidget(self.label_2)
        self.btn_x = QtWidgets.QPushButton(Form)
        self.btn_x.setObjectName("btn_x")
        self.horizontalLayout3.addWidget(self.btn_x)
        self.btn_y = QtWidgets.QPushButton(Form)
        self.btn_y.setObjectName("btn_y")
        self.horizontalLayout3.addWidget(self.btn_y)
        self.btn_z = QtWidgets.QPushButton(Form)
        self.btn_z.setObjectName("btn_z")
        self.horizontalLayout3.addWidget(self.btn_z)
        self.btn_mag = QtWidgets.QPushButton(Form)
        self.btn_mag.setObjectName("btn_mag")
        self.horizontalLayout3.addWidget(self.btn_mag)
        self.verticalLayout.addLayout(self.horizontalLayout3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout4.setObjectName("horizontalLayout4")
        self.verticalLayout.addLayout(self.horizontalLayout4)
        self.verticalLayout.setStretch(3, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_2.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "可靠性分析"))
        item = self.table_content.horizontalHeaderItem(0)
        item.setText(_translate("Form", "模型ID"))
        item = self.table_content.horizontalHeaderItem(1)
        item.setText(_translate("Form", "模型名称"))
        item = self.table_content.horizontalHeaderItem(2)
        item.setText(_translate("Form", "模型文件路径"))
        item = self.table_content.horizontalHeaderItem(3)
        item.setText(_translate("Form", "外部模型路径"))
        self.label_6.setText(_translate("Form", "选择模型ID："))
        self.edit_id_to_del.setText(_translate("Form", "input_file:id"))
        self.label_4.setText(_translate("Form", "基于应力应变的可靠性分析："))
        self.btn_mise_reliability.setText(_translate("Form", "基于应力值"))
        self.btn_press_reliability.setText(_translate("Form", "基于压力值"))
        self.btn_tresca_reliability.setText(_translate("Form", "基于屈服值"))
        self.label_2.setText(_translate("Form", "基于位移变形的可靠性分析："))
        self.btn_x.setText(_translate("Form", "X方向"))
        self.btn_y.setText(_translate("Form", "Y方向"))
        self.btn_z.setText(_translate("Form", "Z方向"))
        self.btn_mag.setText(_translate("Form", "总位移量"))

