# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulate_config_form.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1311, 928)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.table_model = QtWidgets.QTableWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_model.sizePolicy().hasHeightForWidth())
        self.table_model.setSizePolicy(sizePolicy)
        self.table_model.setSizeIncrement(QtCore.QSize(0, 0))
        self.table_model.setBaseSize(QtCore.QSize(0, 0))
        self.table_model.setObjectName("table_model")
        self.table_model.setColumnCount(4)
        self.table_model.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_model.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_model.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_model.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_model.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.table_model, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.table_params = QtWidgets.QTableWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_params.sizePolicy().hasHeightForWidth())
        self.table_params.setSizePolicy(sizePolicy)
        self.table_params.setSizeIncrement(QtCore.QSize(0, 0))
        self.table_params.setBaseSize(QtCore.QSize(0, 0))
        self.table_params.setObjectName("table_params")
        self.table_params.setColumnCount(7)
        self.table_params.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_params.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_params.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_params.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_params.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_params.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_params.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_params.setHorizontalHeaderItem(6, item)
        self.gridLayout_2.addWidget(self.table_params, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.edit_model = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edit_model.setFont(font)
        self.edit_model.setText("")
        self.edit_model.setReadOnly(True)
        self.edit_model.setObjectName("edit_model")
        self.gridLayout_3.addWidget(self.edit_model, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self.edit_params = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edit_params.setFont(font)
        self.edit_params.setText("")
        self.edit_params.setReadOnly(True)
        self.edit_params.setObjectName("edit_params")
        self.gridLayout_3.addWidget(self.edit_params, 1, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_confirm = QtWidgets.QPushButton(Form)
        self.btn_confirm.setObjectName("btn_confirm")
        self.horizontalLayout.addWidget(self.btn_confirm)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btn_start = QtWidgets.QPushButton(Form)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout.addWidget(self.btn_start)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_2.setStretch(1, 1)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "模型列表"))
        item = self.table_model.horizontalHeaderItem(0)
        item.setText(_translate("Form", "模型ID"))
        item = self.table_model.horizontalHeaderItem(1)
        item.setText(_translate("Form", "模型名称"))
        item = self.table_model.horizontalHeaderItem(2)
        item.setText(_translate("Form", "模型文件路径"))
        item = self.table_model.horizontalHeaderItem(3)
        item.setText(_translate("Form", "外部模型路径"))
        self.groupBox_2.setTitle(_translate("Form", "参数列表"))
        item = self.table_params.horizontalHeaderItem(0)
        item.setText(_translate("Form", "参数ID"))
        item = self.table_params.horizontalHeaderItem(1)
        item.setText(_translate("Form", "参数名称"))
        item = self.table_params.horizontalHeaderItem(2)
        item.setText(_translate("Form", "分布类型"))
        item = self.table_params.horizontalHeaderItem(3)
        item.setText(_translate("Form", "位置参数"))
        item = self.table_params.horizontalHeaderItem(4)
        item.setText(_translate("Form", "比例参数"))
        item = self.table_params.horizontalHeaderItem(5)
        item.setText(_translate("Form", "形状参数"))
        item = self.table_params.horizontalHeaderItem(6)
        item.setText(_translate("Form", "单  位"))
        self.label_13.setText(_translate("Form", "选择模型ID："))
        self.label_14.setText(_translate("Form", "选择参数ID："))
        self.btn_confirm.setText(_translate("Form", "确认选择"))
        self.btn_start.setText(_translate("Form", "开始仿真"))
